import {Checker} from '../game-classes/checker'
import {
    STRING_REP_REGULAR_BLACK,
    STRING_REP_EMPTY_SQUARE,
    STRING_REP_REGULAR_WHITE,
    COLOR_PLAYER_ONE,
    COLOR_PLAYER_TWO,
    REGULAR_CHCKER
    
} from './constants'


export const createCheckerClassArray=():Checker [][]=>{
    const classInitialGameState = [
        [new Checker(COLOR_PLAYER_ONE,REGULAR_CHCKER),null,new Checker(COLOR_PLAYER_ONE,REGULAR_CHCKER),null,new Checker(COLOR_PLAYER_ONE,REGULAR_CHCKER),null,new Checker(COLOR_PLAYER_ONE,REGULAR_CHCKER),null],
        [null,new Checker(COLOR_PLAYER_ONE,REGULAR_CHCKER),null,new Checker(COLOR_PLAYER_ONE,REGULAR_CHCKER),null,new Checker(COLOR_PLAYER_ONE,REGULAR_CHCKER),null,new Checker(COLOR_PLAYER_ONE,REGULAR_CHCKER)],
        [new Checker(COLOR_PLAYER_ONE,REGULAR_CHCKER),null,new Checker(COLOR_PLAYER_ONE,REGULAR_CHCKER),null,new Checker(COLOR_PLAYER_ONE,REGULAR_CHCKER),null,new Checker(COLOR_PLAYER_ONE,REGULAR_CHCKER),null],
        [null,null,null,null,null,null,null,null],
        [null,null,null,null,null,null,null,null],
        [null,new Checker(COLOR_PLAYER_TWO,REGULAR_CHCKER),null,new Checker(COLOR_PLAYER_TWO,REGULAR_CHCKER),null,new Checker(COLOR_PLAYER_TWO,REGULAR_CHCKER),null,new Checker(COLOR_PLAYER_TWO,REGULAR_CHCKER)],
        [new Checker(COLOR_PLAYER_TWO,REGULAR_CHCKER),null,new Checker(COLOR_PLAYER_TWO,REGULAR_CHCKER),null,new Checker(COLOR_PLAYER_TWO,REGULAR_CHCKER),null,new Checker(COLOR_PLAYER_TWO,REGULAR_CHCKER),null],
        [null,new Checker(COLOR_PLAYER_TWO,REGULAR_CHCKER),null,new Checker(COLOR_PLAYER_TWO,REGULAR_CHCKER),null,new Checker(COLOR_PLAYER_TWO,REGULAR_CHCKER),null,new Checker(COLOR_PLAYER_TWO,REGULAR_CHCKER)] 
    
    ]
    return classInitialGameState
}

export const createStringInitialGameState=():string [][]=>{
     const stringInitialGameState = [
        [STRING_REP_REGULAR_BLACK,STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_BLACK,STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_BLACK,STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_BLACK,STRING_REP_EMPTY_SQUARE],
        [STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_BLACK,STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_BLACK,STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_BLACK,STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_BLACK],
        [STRING_REP_REGULAR_BLACK,STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_BLACK,STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_BLACK,STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_BLACK,STRING_REP_EMPTY_SQUARE],
        [STRING_REP_EMPTY_SQUARE,STRING_REP_EMPTY_SQUARE,STRING_REP_EMPTY_SQUARE,STRING_REP_EMPTY_SQUARE,STRING_REP_EMPTY_SQUARE,STRING_REP_EMPTY_SQUARE,STRING_REP_EMPTY_SQUARE,STRING_REP_EMPTY_SQUARE],
        [STRING_REP_EMPTY_SQUARE,STRING_REP_EMPTY_SQUARE,STRING_REP_EMPTY_SQUARE,STRING_REP_EMPTY_SQUARE,STRING_REP_EMPTY_SQUARE,STRING_REP_EMPTY_SQUARE,STRING_REP_EMPTY_SQUARE,STRING_REP_EMPTY_SQUARE],
        [STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_WHITE,STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_WHITE,STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_WHITE,STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_WHITE],
        [STRING_REP_REGULAR_WHITE,STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_WHITE,STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_WHITE,STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_WHITE,STRING_REP_EMPTY_SQUARE],
        [STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_WHITE,STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_WHITE,STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_WHITE,STRING_REP_EMPTY_SQUARE,STRING_REP_REGULAR_WHITE]
    ]
    return stringInitialGameState
}